version: "3.8"

services:
  nxerra-crm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb+srv://ranjanshashank:IvNaKKZUjV1VLctr@cluster0.9sbiuik.mongodb.net/
      - JWT_SECRET=ABJSECRET@2025TH

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
